server.host=127.0.0.1
server.port=9999
auth.timestamp.window.ms=30000
openvpn.exe.win=C:\\Program Files\\OpenVPN\\bin\\openvpn.exe
openvpn.exe.mac=/opt/homebrew/sbin/openvpn
openvpn.exe.linux=/usr/sbin/openvpn
listenPort=8888
forwardHost=127.0.0.1
forwardPort=9999
path.users=data/users.txt
path.history=data/login_history.txt
path.auth=vpn-auth.txt
config.dir=openvpn-configs
